FROM node:20-alpine AS build

WORKDIR /usr/src/blog-frontend

COPY BlogFrontend/React-frontend/package*.json ./

RUN npm install

COPY BlogFrontend/React-frontend/ .

RUN npm run build

FROM nginx:stable-alpine

COPY --from=build /usr/src/blog-frontend/dist /usr/share/nginx/html

COPY BlogFrontend/React-frontend/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
